CREATE DATABASE IF NOT EXISTS iglesia_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE iglesia_db;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NULL,
  role ENUM('ADMIN','GENERIC') NOT NULL DEFAULT 'GENERIC',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS members (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(20) NOT NULL UNIQUE,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  date_of_birth DATE NULL,
  address VARCHAR(200) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(120) NULL,
  is_baptized TINYINT(1) NOT NULL DEFAULT 0,
  join_date DATE NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS baptisms (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  member_id BIGINT UNSIGNED NOT NULL UNIQUE,
  baptism_date DATE NOT NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_baptisms_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  type ENUM('MEMBER_CREATE','MEMBER_UPDATE','MEMBER_DELETE','BAPTISM_CREATE','BAPTISM_UPDATE','BAPTISM_DELETE','USER_CREATE','USER_ROLE_UPDATE') NOT NULL,
  target_table VARCHAR(64) NULL,
  target_id BIGINT UNSIGNED NULL,
  payload TEXT NOT NULL,
  submitted_by BIGINT UNSIGNED NOT NULL,
  status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  reason TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decision_at DATETIME NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  INDEX (status), INDEX (type),
  CONSTRAINT fk_requests_submitted_by FOREIGN KEY (submitted_by) REFERENCES users(id),
  CONSTRAINT fk_requests_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id)
) ENGINE=InnoDB;

INSERT INTO users (username, password, full_name, email, role)
VALUES ('admin', 'admin123', 'Administrador Principal', 'admin@iglesia.local', 'ADMIN')
ON DUPLICATE KEY UPDATE username = username;
